#' Pivot (bi-graph) triples into (bi-adjacency) matrix
#'
#' Converts a data frame of triples (`x_names`, `y_names`, `values`) into
#' a matrix with `x_names` and `y_names` respectively
#' for row and column names and cell values from `values`.
#'
#' The triples define graph edges between `x_names` and `y_names` with
#' attribute `value`. `x_names` and `y_names` are treated as disjoint nodes sets
#' of the bi-partite graph,
#' and the resultant matrix corresponds to the bi-adjacency matrix.
#'
#' Uses \link[tidyr]{pivot_wider} and makes explicit
#' all possible pairs of `x_names` and `y_names`.
#'
#' @param triples A data frame to pivot. Unused columns are dropped.
#' @param x_names_from column to get matrix row row names from.
#' @param y_names_from column to get matrix column names from.
#' @param values_from column to get cell values from.
#' @inheritParams tidyr::pivot_wider
#'
#' @export
#'
#' @examples
#' triples$blx_tbl
#'
#' triples$blx_tbl |>
#'   triples_to_matrix(from, to, weighted)
triples_to_matrix <- function(triples,
                              x_names_from = x_name,
                              y_names_from = y_name,
                              values_from = value,
                              values_fill = NA){

  triples_wide <- triples |>
    tidyr::pivot_wider(names_from={{y_names_from}},
                       values_from={{values_from}},
                       values_fill=values_fill)

  x_dim <- nrow(triples_wide)
  x_names <- triples_wide[[1]]
  y_names <- names(triples_wide[,-1])

  mtx <- triples_wide[, -1] |>
    unlist() |>
    matrix(nrow=x_dim)

  dimnames(mtx) <- list(x_names, y_names)

  mtx
}

#' Pivots a matrix into (bi-graph) triples
#'
#' Converts a named (adjacency) matrix into (graph) triples,
#' dropping any NA cells by default.
#'
#' Uses \link[tidyr]{pivot_longer} and reverses [triples_to_matrix()].
#' Setting `drop_na=FALSE` retain the complete set of graph edges.
#' If `matrix` is unnamed, default names are generated by [base::as.data.frame()]
#'
#' @param matrix A matrix to pivot
#' @param x_names_to A string specifying the new column for
#' the names of the first/x-dimension of `matrix`
#' @param y_names_to A string specifying the new column for
#' the names of the second/y-dimension  `matrix`
#' @param values_to A character vector specifying the new column to create
#' from the cell values of `matrix`
#' @param drop_na Boolean option to drop `x`-`y` pairs with missing values.
#'
#' @export
#'
#' @examples
#'
#' ## named matrices
#' blx_mtx <- triples$blx_tbl |>
#'   triples_to_matrix(from, to, weighted)
#' return_triples <- blx_mtx |>
#'   triples_from_matrix("from", "to", "weighted")
#'
#' identical(triples$blx_tbl, return_triples)
#'
#' ## Setting `drop_na=FALSE` retains the `x`-`y` pairs with missing values,
#' return_with_na <- blx_mtx |>
#'   triples_from_matrix("from", "to", "weighted", drop_na = FALSE)
#'
#' ## which is equivalent to using `tidyr::complete()` on the original triples
#' complete_triples <- triples$blx_tbl |>
#'   tidyr::complete(from, to)
#'
#' identical(return_with_na, complete_triples)
#'
#' ## names are generated for unnamed matrices
#' matrices$unnamed |>
#'   matrix_to_triples(drop_na = FALSE)
matrix_to_triples <- function(matrix,
                                x_names_to = "x_name",
                                y_names_to = "y_name",
                                values_to = "value",
                                drop_na=TRUE){
  x_names <- dimnames(matrix)[[1]]
  y_names <- dimnames(matrix)[[2]]

  mtx_df <- as.data.frame(matrix) |>
    tibble::rownames_to_column(var = x_names_to) |>
    tidyr::pivot_longer(-c(x_names_to),
                        names_to = y_names_to,
                        values_to = values_to)
  if (drop_na) {
    mtx_df |>
      tidyr::drop_na(tidyselect::all_of(c(values_to)))
  } else {
    mtx_df
  }

}

if (FALSE){

}
